apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: falamarcaodocker/kube-data-demo:3
          env:
            - name: STORY_FOLDER
              # value: 'story'
              valueFrom:
                configMapKeyRef: 
                  name: env-vars # see environment.yaml file
                  key: folder
          volumeMounts:
            - mountPath: /app/story
              name: story-volume
      volumes:
        - name: story-volume
          # emptyDir: {} # creates a empty directory per pod and survices container restart, but pods don't share data.
          # hostPath: # creates a path in the host machine (host and pods shares data) - works for multiple pods, but only pods on same worker node has access.
          #   path: /data
          #   type: DirectoryOrCreate # if not exists, creates a directory
          persistentVolumeClaim:
            claimName: host-pvc # name in `host-pvc.yaml`